### ISSUE TITLE
Make has to be interrupted

### ISSUE THREAD

**Issue by borpin** [TradeFace/gismocaster#59]
On development branch. Updated repo with `git pull`.

Running make (having modified the mqtt settings for an existing Broker, I get many, many MQTT messages. requires Ctl-C to stop and presumably `make` does not finish?

```
2020-08-05 12:42:16,033 DEBUG    [paho.mqtt.client] Sending PUBLISH (d0, q0, r1, m1825), 'b'tuyagateway/config/homeassistant/climate'', ... (9924 bytes)
2020-08-05 12:42:16,037 DEBUG    [mqtt.mqtt] Publishing tuyagateway/config/homeassistant/fan {"values": [], "topics": [], "templates": []} True
2020-08-05 12:42:16,037 DEBUG    [paho.mqtt.client] Sending PUBLISH (d0, q0, r1, m1826), 'b'tuyagateway/config/homeassistant/fan'', ... (45 bytes)
2020-08-05 12:42:16,040 DEBUG    [mqtt.mqtt] Publishing tuyagateway/config/homeassistant/device_automation {"values": [], "topics": [], "templates": []} True
2020-08-05 12:42:16,041 DEBUG    [paho.mqtt.client] Sending PUBLISH (d0, q0, r1, m1827), 'b'tuyagateway/config/homeassistant/device_automation'', ... (45 bytes)
2020-08-05 12:42:16,044 DEBUG    [mqtt.mqtt] Publishing tuyagateway/config/homeassistant/cover {"values": [], "topics": [], "templates": []} True
2020-08-05 12:42:16,044 DEBUG    [paho.mqtt.client] Sending PUBLISH (d0, q0, r1, m1828), 'b'tuyagateway/config/homeassistant/cover'', ... (45 bytes)
2020-08-05 12:42:16,047 DEBUG    [mqtt.mqtt] Publishing tuyagateway/config/homeassistant/camera {"values": [], "topics": [], "templates": []} True
2020-08-05 12:42:16,047 DEBUG    [paho.mqtt.client] Sending PUBLISH (d0, q0, r1, m1829), 'b'tuyagateway/config/homeassistant/camera'', ... (45 bytes)
2020-08-05 12:42:16,054 DEBUG    [mqtt.mqtt] Publishing tuyagateway/config/homeassistant/binary_sensor {"values": [], "topics": [{"name": "availability_topic", "abbreviation": "avty_t", "topic_type": "publish", "default_value": "~availability", "values": [{"name": "payload_available", "abbreviation": "pl_avail", "type_value": "string", "default_value": "online", "tuya_value": true}, {"name": "payload_not_available", "abbreviation": "pl_not_avail", "type_value": "string", "default_value": "offline", "tuya_value": false}]}, {"name": "json_attributes_topic", "abbreviation": "json_attr_t", "topic_type": "publish", "default_value": "~attributes", "values": []}, {"name": "state_topic", "abbreviation": "stat_t", "topic_type": "publish", "default_value": "~state", "values": [{"name": "state_off", "abbreviation": "stat_off", "type_value": "string", "default_value": "OFF", "tuya_value": false}, {"name": "state_on", "abbreviation": "stat_on", "type_value": "string", "default_value": "ON", "tuya_value": true}]}], "templates": [{"name": "state_template", "abbreviation": "stat_tpl", "default_value": ""}, {"name": "value_template", "abbreviation": "val_tpl", "default_value": ""}]} True
2020-08-05 12:42:16,054 DEBUG    [paho.mqtt.client] Sending PUBLISH (d0, q0, r1, m1830), 'b'tuyagateway/config/homeassistant/binary_sensor'', ... (1081 bytes)
2020-08-05 12:42:16,058 DEBUG    [mqtt.mqtt] Publishing tuyagateway/config/homeassistant/alarm_control_panel {"values": [], "topics": [], "templates": []} True
2020-08-05 12:42:16,058 DEBUG    [paho.mqtt.client] Sending PUBLISH (d0, q0, r1, m1831), 'b'tuyagateway/config/homeassistant/alarm_control_panel'', ... (45 bytes)
2020-08-05 12:42:16,067 DEBUG    [mqtt.mqtt] Publishing tuyagateway/config/homeassistant/switch {"values": [], "topics": [{"name": "availability_topic", "abbreviation": "avty_t", "topic_type": "publish", "default_value": "~availability", "values": [{"name": "payload_available", "abbreviation": "pl_avail", "type_value": "string", "default_value": "online", "tuya_value": true}, {"name": "payload_not_available", "abbreviation": "pl_not_avail", "type_value": "string", "default_value": "offline", "tuya_value": false}]}, {"name": "command_topic", "abbreviation": "cmd_t", "topic_type": "subscribe", "default_value": "~command", "publish_topic": "state_topic", "values": [{"name": "payload_off", "abbreviation": "pl_off", "type_value": "string", "default_value": "OFF", "tuya_value": false}, {"name": "payload_on", "abbreviation": "pl_on", "type_value": "string", "default_value": "ON", "tuya_value": true}]}, {"name": "state_topic", "abbreviation": "stat_t", "topic_type": "publish", "default_value": "~state", "values": [{"name": "state_off", "abbreviation": "stat_off", "type_value": "string", "default_value": "OFF", "tuya_value": false}, {"name": "state_on", "abbreviation": "stat_on", "type_value": "string", "default_value": "ON", "tuya_value": true}]}], "templates": [{"name": "json_attributes_template", "abbreviation": "json_attr_tpl", "default_value": ""}, {"name": "state_template", "abbreviation": "stat_tpl", "default_value": ""}, {"name": "value_template", "abbreviation": "val_tpl", "default_value": ""}]} True
2020-08-05 12:42:16,067 DEBUG    [paho.mqtt.client] Sending PUBLISH (d0, q0, r1, m1832), 'b'tuyagateway/config/homeassistant/switch'', ... (1424 bytes)
^CTraceback (most recent call last):
  File "web/manage.py", line 21, in <module>
    main()
  File "web/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/loaddata.py", line 181, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python3.8/dist-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 793, in save_base
    post_save.send(
  File "/usr/local/lib/python3.8/dist-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/usr/local/lib/python3.8/dist-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/gismocaster/web/mqtt/signals.py", line 73, in save_tvalue
    mqtt.publish_transformers()
  File "/opt/gismocaster/web/mqtt/mqtt.py", line 268, in publish_transformers
    _publish_transformer(component)
  File "/opt/gismocaster/web/mqtt/mqtt.py", line 248, in _publish_transformer
    for item in list(TopicValue.objects.filter(topic_id=topicid).values())
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 115, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1104, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1139, in execute_sql
    sql, params = self.as_sql()
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 491, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 51, in pre_sql_setup
    self.setup_query()
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 42, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 263, in get_select
    sql, params = col.select_format(self, sql, params)
KeyboardInterrupt
make: *** [Makefile:4: init] Interrupt
```

**Comment by TradeFace** [comment]
The mqtt settings are deliberately empty in the fixtures to prevent this problem. It should finish without problems though
